### ISSUE TITLE
Add support for 'list_integer' field types

### ISSUE THREAD

**Issue by ericfg** [backdrop-contrib/multiselect#1]
moving over some issues from the drupal queue 
https://www.drupal.org/project/multiselect/issues/2188473

**Comment by klonos** [comment]
Cross-posting what I just posted in https://www.drupal.org/project/multiselect/issues/2188473#comment-14843968

> TL;DR: This is simply a matter of whether you want things to not break in older D7 sites that have started as pre-release/dev sites before Drupal 7 was officially released, and have not been updated properly when D7.0 was officially released.
> 
> As part of [#932502: Changing allowed values in "List" fields](https://www.drupal.org/project/drupal/issues/932502), an update hook was introduced, which renamed field types from `'list'` to `'list_integer'`, and from `'list_number'` to  `'list_float'`. So the only sites where `'list_number'` will make sense are the ones where the core `list_update_7001()` hook was not run ([this hook exists since D7.0](https://git.drupalcode.org/project/drupal/-/blob/7.0/modules/field/modules/list/list.install#L77)).
> 
> Bottom line is that if you want things to work properly, then the only types used in properly updated D7 sites are `'list_integer'` and `'list_float'` - there's no `'list'` or `'list_number'` any more - these were a thing in D6 I guess, and only available in D7 RC2 if we go by the inline comment [here](https://git.drupalcode.org/project/drupal/-/blob/7.0/modules/field/modules/list/list.install#L95).
> 
> I hope the above helps unblock this issue here. I will see if I an provide a PR for it.

**Comment by klonos** [comment]
Here's a PR for review: https://github.com/backdrop-contrib/multiselect/pull/11

PS: I haven't fixed the respective text in `multiselect_help()`, since that should be removed altogether (see #6 ).

**Comment by herbdool** [comment]
This looks good @klonos. I made one small fix to your PR. You removed `node_reference` for some reason and it should stay.

**Comment by argiepiano** [comment]
Merged on behalf of the @backdrop-contrib/bug-squad
