### ISSUE TITLE
Remove multiselect_help()

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/multiselect#6]
`hook_help()` has been removed from Backdrop, so best to remove it from the module.

See: https://docs.backdropcms.org/converting-modules-from-drupal#core-modules-removed
> A commonly-used Drupal function was `hook_help()` in modulename.module. As the Help module was removed from Backdrop, this function no longer exists and so you should instead display any necessary help text on forms/pages directly, or in your module's GitHub Wiki.
>
> Leaving these hooks in your code will not affect a Backdrop module in any way, since the code will simply not be called. You may leave them in place if you would like to be able run the same module on both Drupal and Backdrop sites.

**Comment by klonos** [comment]
@ericfg PR for review when you get  chance: https://github.com/backdrop-contrib/multiselect/pull/7

**Comment by argiepiano** [comment]
Reviewed on behalf of the bug squad. LGTM and RTBC.

**Comment by argiepiano** [comment]
I messed up your PR, @klonos. Providing a new PR, since I don't know how to fix.
