### ISSUE TITLE
Add link to configuration page from the module entry in the modules listing page.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/multiselect#8]
Adding a `configure = admin/config/content/multiselect` line in the .info file of the module should do that:
![image](https://user-images.githubusercontent.com/2423362/209524921-a14bf1ce-6c3e-47a2-9c99-8b239f52a186.png)

**Comment by klonos** [comment]
PR up for review @ericfg (when you get the chance): https://github.com/backdrop-contrib/multiselect/pull/9

**Comment by argiepiano** [comment]
Reviewing on behalf of the bug squad. LGTM and RTB!

**Comment by argiepiano** [comment]
Merged on behalf of the @backdrop-contrib/bug-squad
